app:
  id: 1
  name: game-service
  version: 1.0
  is_dev: true
  log_level: debug
  is_log_json: true

redis:
  address: localhost:6379
  password: ""
  db: 0
  tls: false
  max_attempts: 3
  max_delay: 3s

grpc:
  host: 0.0.0.0
  port: 9994
  health_check_interval: 10s

http:
  host: 0.0.0.0
  port: 8082
  read_header_timeout: 3s

nats:
  enable: true
  debug: true
  tracing: true
  auth:
    is_enabled: true
    username: ruser
    password: T0pS3cr3t
  urls:
    - nats://localhost:30026
    - nats://localhost:4222
  timeout: 2s
  max_ack_pending: 2s
  consumer_id: game-service
  notifications:
    subject: notifications
    bonus_service:
      enabled: true
  streams:
    bet_events:
      enabled: true
      name: BETS
      subjects:
        bet: aggregate
    game_events:
      enabled: true
      name: GAMES
      subjects:
        new: new
        updated: updated

postgres:
  host: 127.0.0.1
  user: postgres
  password: testtest
  port: 5432
  database: game
  max_attempt: 3
  max_delay: 3s
  binary: false

minio:
  host: 0.0.0.0
  port: 9000
  access_key_id: minio
  secret_access_key: minio123
  game_images_bucket_name: game-images

metrics:
  host: 0.0.0.0
  port: 8081
  read_timeout: 3s
  write_timeout: 3s
  read_header_timeout: 3s
  enabled: true

tracing:
  enabled: true
  host: 0.0.0.0
  port: 4318
